-- 코드를 입력하세요
SELECT 
    YEAR(o.SALES_DATE) AS YEAR, 
    MONTH(o.SALES_DATE) AS MONTH, 
    u.GENDER, 
    COUNT(DISTINCT o.USER_ID) AS USERS
FROM USER_INFO AS u
RIGHT JOIN ONLINE_SALE AS o
    ON u.USER_ID = o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR, MONTH, u.GENDER;