-- 코드를 입력하세요
SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES JOIN
(SELECT HOST_ID
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(HOST_ID) > 1) AS B
ON PLACES.HOST_ID = B.HOST_ID
ORDER BY PLACES.ID;