SELECT 
    A.HISTORY_ID, 
    FLOOR(A.DAILY_FEE * A.BORROW_DATE * (100 - IFNULL(B.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (
    SELECT 
        H.HISTORY_ID,
        R.DAILY_FEE,
        (CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7  THEN '7일 이상'
            ELSE '0일'
        END) AS DURATION_TYPE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS BORROW_DATE
    FROM CAR_RENTAL_COMPANY_CAR AS R
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
      ON R.CAR_ID = H.CAR_ID
    WHERE R.CAR_TYPE = '트럭'
) AS A
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) AS B
  ON A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;