SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
CROSS JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE "Front End") AS S
ON (D.SKILL_CODE & S.CODE) = S.CODE
ORDER BY ID;