-- 코드를 입력하세요
SELECT A.CAR_ID
FROM (SELECT CAR_ID, CAR_TYPE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE='세단') AS A
JOIN 
(SELECT DISTINCT CAR_ID, MONTH(START_DATE)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE)='10') AS B
ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC;