SELECT F.ID, FN.FISH_NAME, F.LENGTH
FROM (  SELECT A.ID, A.FISH_TYPE, A.LENGTH
        FROM FISH_INFO AS A 
        JOIN (  SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
                FROM FISH_INFO
                GROUP BY FISH_TYPE) AS B
        ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.MAX_LEN) AS F
JOIN FISH_NAME_INFO AS FN
ON F.FISH_TYPE = FN.FISH_TYPE
ORDER BY F.ID;


