SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
JOIN
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY
HAVING CATEGORY IN ("과자", "국", "김치", "식용유")) AS MP
ON F.PRICE = MP.MAX_PRICE AND F.CATEGORY = MP.CATEGORY
ORDER BY F.PRICE DESC;
